apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
spec:
  selector:
    matchLabels:
      app: netshoot
  replicas: 1
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        args:
        - -c
        - while true; do sleep 86400; done
        securityContext:
          privileged: false
          capabilities:
            add: ["ALL"]
