version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "88:88"
    networks:
      - mail
    volumes:
      - "/data/nginx/conf.d:/etc/nginx/conf.d"
      - "/data/nginx/ssl:/etc/nginx/ssl"
    #environment:
    #  - "LETSENCYPT=false"
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  mysql:
    image: mysql:8
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    networks:
      - mail
    volumes:
      - "/data/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "Kf4cxbZpdLMj3ux9kwP53c3e"
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  exim4:
    build:
      dockerfile: Dockerfile.exim
      context: ./
    image: golovanovsv/exim4
    container_name: exim4
    hostname: exim4
    restart: unless-stopped
    ports:
      - "25:25"
    networks:
      - mail
    volumes:
      - "/data/mail:/opt/vmail"
      - "/data/exim/exim4.conf:/etc/exim4/exim4.conf"
      - "/data/exim/blocked_users:/etc/exim4/blocked_users"
      - "/data/exim/domain_black_list:/etc/exim4/domain_black_list"
      - "/var/log/exim4:/var/log/exim4"
      - "/data/nginx/ssl:/etc/certificates"
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  rspamd:
    build:
      dockerfile: Dockerfile.rspamd
      context: ./
    image: golovanovsv/rspamd
    container_name: rspamd
    hostname: rspamd
    restart: unless-stopped
    networks:
      - mail
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  dovecot:
    build:
      dockerfile: Dockerfile.dovecot
      context: ./
    image: golovanovsv/dovecot
    container_name: dovecot
    hostname: dovecot
    restart: unless-stopped
    ports:
      - "110:110"
      - "143:143"
    networks:
      - mail
    volumes:
      - "/data/mail:/opt/vmail"
      - "/data/nginx/ssl:/etc/certificates"
      - "/data/dovecot/dovecot-sql.conf:/etc/dovecot/dovecot-sql.conf"
      - "/data/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf"
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  roundcube:
    image: roundcube/roundcubemail:latest-apache
    container_name: roundcube
    hostname: roundcube
    restart: unless-stopped
    networks:
      - mail
    #volumes:
    environment:
      ROUNDCUBEMAIL_DB_TYPE: "mysql"
      ROUNDCUBEMAIL_DB_HOST: "mysql"
      ROUNDCUBEMAIL_DB_USER: "roundcube"
      ROUNDCUBEMAIL_DB_PASSWORD: "q7JAu3VBhwkYS5BD"
      ROUNDCUBEMAIL_DB_NAME: "roundcube"
      ROUNDCUBEMAIL_DEFAULT_HOST: "dovecot"
      ROUNDCUBEMAIL_SMTP_SERVER: "exim4"
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

  vfront:
    build:
      dockerfile: Dockerfile.vfront
      context: ./
    image: golovanovsv/vfront
    container_name: vfront
    hostname: vfront
    restart: unless-stopped
    networks:
      - mail
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: "10m"

networks:
  mail: