version: "3.8"
services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    network_mode: "host"
  
  kafka-1:
    image: bitnami/kafka
    container_name: kafka-1
    depends_on:
      - zookeeper
    network_mode: "host"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_BROKER_ID: 100
      KAFKA_CFG_NUM_PARTITIONS: 10
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9092"
  
  kafka-2:
    image: bitnami/kafka
    container_name: kafka-2
    depends_on:
      - zookeeper
    network_mode: "host"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_BROKER_ID: 200
      KAFKA_CFG_NUM_PARTITIONS: 10
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://127.0.0.1:9093"
