version: "3.8"
services:
  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - /data/prometheus:/data/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/data/prometheus
      - --storage.tsdb.retention.time=168h
      - --web.enable-lifecycle
    restart: unless-stopped
    networks:
      - prometheus
    ports:
      - 9090:9090

networks:
  prometheus:
