apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  namespace: test
spec:
  selector:
    matchLabels:
      app: netshoot
  replicas: 1
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        args:
        - -c
        - while true; do sleep 86400; done
        securityContext:
          privileged: true
          capabilities:
            add: ["ALL"]
        startupProbe:
          exec:
            command:
            - cat 
            - /etc/os-release
